### ISSUE TITLE
[BUG] Leftover `info` call is too verbose

### ISSUE THREAD

**Issue by brooksmtownsend** [gin66/tui-logger#15]
Hey there!

Looks like the latest version of `tui_logger` includes an `info` call that's very noisy for users:
https://github.com/gin66/tui-logger/blob/master/src/lib.rs#L942-L946

I can certainly adjust the verbosity of `tui_logger` for my log levels, but I feel like this might've just been leftover from a previous version 🙂 I'll put in a PR removing the log, but I'd be happy to adjust it to `trace` if you need that information for something else

**Comment by brooksmtownsend** [comment]
@gin66 Is there anything holding this back from being released as `0.6.3`?

**Comment by gin66** [comment]
Only some redactional changes, which I only can do at my computer with the repo on it.
Just have published `0.6.3`
