### ISSUE TITLE
Add the ability to specify log message formatting

### ISSUE THREAD

**Issue by jcredmond** [gin66/tui-logger#19]
I think tui-logger would greatly benefit from the ability to customize the format of logged messages. It seems that the message format is [hardcoded](https://github.com/gin66/tui-logger/blob/62d0594a9112d375487a060ea1a6987037d5ed92/src/lib.rs#L908). In my specific case, I'm logging messages from multiple child processes that are sent back to the parent via a pipe. For things like warnings and errors, the "location" that the log is printed from is of no use because it's the same line(s) every time (the place in the parent where the message is read from the pipe and logged in the parent). Additionally, in my case, the logging of the target is redundant noise and I would prefer if it wasn't there. Finally, in long running processes, I can see where H:M:S time stamps aren't enough (think about a process that has uptime in the days, weeks, or longer).

In the absence of a formal way to specify the formatting a simple compromise would be a "passthrough" mode that just logs the string passed to log without any additional formatting or text added (but keeps the coloring / style set).

**Comment by gin66** [comment]
The output is hardcoded [here](https://github.com/gin66/tui-logger/blob/62d0594a9112d375487a060ea1a6987037d5ed92/src/lib.rs#L908).

If the sequence of fields is acceptable, then the Y-M-D could be added as another "field". With the use of a handful boolean flags the individual fields could be turned off. Perhaps like this:
```
    let tui_sm = TuiLoggerSmartWidget::default()
        .style_error(Style::default().fg(Color::Red))
        .style_debug(Style::default().fg(Color::Green))
        .style_warn(Style::default().fg(Color::Yellow))
        .style_trace(Style::default().fg(Color::Magenta))
        .style_info(Style::default().fg(Color::Cyan))
        .output_YMD(true)
        .output_HMS(true)
        .output_target(false)
        .output_file(false)
        .output_line(false)
        .state(&mut app.states[sel]);
```

Something like this ?

**Comment by gin66** [comment]
Just have released v0.6.6 with similar implementation
See (https://github.com/gin66/tui-logger/blob/master/CHANGELOG.md)

Hope this fulfills your needs.

**Comment by gin66** [comment]
BTW: The log messages of the Child processes would be more useful, if the whole Log::Record is sent down the pipe instead of the message text only. Then hand it over to TuiLogger with TUI_LOGGER::log(&record)

**Comment by jcredmond** [comment]
Thanks for the very quick turnaround. I looked through the change and I'm pretty confident this will get me what I need.

I'm going to send over more info from the child processes to fill things out, but since these child processes are short lived things like the timestamp didn't make a lot of sense. I'm hoping to be able to use the child process id for the target, for example.

My original plan was to create a tab for each child process and have a log view for each process routing the log messages to a queue/view per-process, but I don't think that's possible with the way things are architected. I can get by with a single log view with interleaved logs from all of the child processes. If this is something that may interest you I can open an issue to discuss that.

**Comment by gin66** [comment]
If additional information is needed to be channeled through the logging machinery, then a feature flag to the crate could be added. The log() function copies the log information into an ExtLogRecord and that could be extended easily by adding static info like a PID, or child name, or just an enum as representative for the Child type. Current implementation for illustration:

```
    fn log(&self, record: &Record) {
        if self.enabled(record.metadata()) {
            let log_entry = ExtLogRecord {
                timestamp: chrono::Local::now(),
                level: record.level(),
                target: record.target().to_string(),
                file: record.file().unwrap_or("?").to_string(),
                line: record.line().unwrap_or(0),
                msg: format!("{}", record.args()),
            };
            self.hot_log.lock().events.push(log_entry);
        }
    }
```

Interesting would be a stripped down project, which could be added as an example to this crate (MIT licensed). Other users could take this as an idea, how interprocess logging could be accomplished.

**Comment by jcredmond** [comment]
Yes, a stripped down example would be great. My current system is Windows only with the main process being in Rust and the child processes being in C++. I open Windows named pipes to each child and the C++ code sends JSON messages back to the parent Rust process which uses serde_json to create the various message type structs (one of which is a log message). I suspect the example should be cross platform and all Rust, so it would take some work to implement that. I'm open to do it at some point if you'd like.

In my case, ideally I could send the whole ExtLogRecord from the child as JSON and use serde_json to reconstruct an ExtLogRecord. The issue with that is there is a time delay between when the message happens in the child and when it is printed in the parent. If the child sends back a timestamp, the parent as currently implemented doesn't use it -- it replaces it with the current timestamp. If the user wanted to go to the child's log file in the filesystem the timestamps wouldn't match. So I think the best approach if I want timestamps would be to use the timestamp in the record if it is present. Does that make sense?

Do you have any thoughts on perhaps having each child process log to its own log view in the parent?

**Comment by jcredmond** [comment]
BTW, how did you envision the TUI_LOGGER::log(&record) concept to work to log full records from the child processes? AFAICT, TUI_LOGGER is private.

**Comment by gin66** [comment]
You're right, TUI_LOGGER is private. Nevertheless it can be retrieved as generic instance of Logger with `logger()` from log-crate.

This works:
```rust
        use log::*;
        logger().log(&Record::builder()
                             .level(Level::Debug)
                             .target("hit")
                             .args(format_args!("Message with {}","argument"))
                             .line(Some(42))
                             .build());
```

**Comment by gin66** [comment]
In case you refer to adding further info to the `ExtLogRecord`, then this crate need to be patched and `TUI_LOGGER` can become public. Or make `hot_log` accessible.

**Comment by jcredmond** [comment]
I think it's fine to use the generic instance of Logger. In my case I think I will just format the message in the child and send over the string since I want the timestamp in the child not in the parent.

**Comment by gin66** [comment]
nothing to add
