### ISSUE TITLE
How to set log format for log file?

### ISSUE THREAD

**Issue by WestXu** [gin66/tui-logger#25]
I want to include millisecond in the timestamp of log file. It seems that tui-logger doesn't expose this function for file log, buy only `output_timestamp` for tui. 

Cool project!

**Comment by gin66** [comment]
Your are right. The timestamp is still hardcoded for file output. 

There could be three possibilities:
- add a setter for the timestamp format string
- add a setter to provide a function of type `Fn(&ExtLogRecord)->String`, which performs the actual formatting and gets an ExtLogRecord. This would require ExtLogRecord to be made public.
- add a setter to provide a function of type `Fn(File, &ExtLogRecord)`, which writes the ExtOogRecord in any format to the file. This would require ExtLogRecord to be made public, too

**Comment by WestXu** [comment]
Well, sounds like a tough decision. Appreciate the hard work and deliberate thoughts on design. ❤️

I currently forked it and changed the hardcoded fmt string for my own use.

**Comment by kdheepak** [comment]
The same tracing event calls results in a seemingly random order in `tui-logger`:

<img width="1512" alt="image" src="https://github.com/gin66/tui-logger/assets/1813121/0ba049f5-b548-4df9-8d9e-4060486abef7">

but in the file output using `tracing_subscriber` it is always the same:

<img width="882" alt="image" src="https://github.com/gin66/tui-logger/assets/1813121/6d3e710f-ecd5-4363-86b8-97ea2ed069de">

Do you know why this might be the case? It makes debugging a little hard some times, if the text is wrapped and there's lots of output, I'm not able to skim through the output in the logs to see what is going on.

I'm using a tracing macro call like so `trace_dbg!(action);`. The macro implementation is the following:

```rust
#[macro_export]
macro_rules! trace_dbg {
    (target: $target:expr, level: $level:expr, $ex:expr) => {{
        match $ex {
            value => {
                tracing::event!(target: $target, $level, ?value, stringify!($ex));
                value
            }
        }
    }};
    (level: $level:expr, $ex:expr) => {
        trace_dbg!(target: module_path!(), level: $level, $ex)
    };
    (target: $target:expr, $ex:expr) => {
        trace_dbg!(target: $target, level: tracing::Level::DEBUG, $ex)
    };
    ($ex:expr) => {
        trace_dbg!(level: tracing::Level::DEBUG, $ex)
    };
}
```

**Comment by gin66** [comment]
Judging by the timestamp, which is generated during log creation, the order of the messages seem to be fine.

**Comment by kdheepak** [comment]
My bad, not the order of the messages itself but the order of the content in each message. ie in some messages action is printed before and in others it is printed after the value.

**Comment by gin66** [comment]
Thanks for clarification. The message, you refer to, is within tui-logger just a string. So the scrambling must come from the tracing interface. Perhaps @ahadnagy can comment on this, as I do not use tracing.

**Comment by gin66** [comment]
stale

**Comment by andrei-ng** [comment]
@kdheepak, @gin66 Stumbled upon the same issue and made this PR #78
