### ISSUE TITLE
How can i display logs from another file

### ISSUE THREAD

**Issue by EnricoMucelli** [gin66/tui-logger#27]
I have a file in main.rs with logs then in another directory i have tui logger, how can i pass to tui-logger the logs to be displayed on the terminal?

**Comment by EnricoMucelli** [comment]
@gin66 can you help me please?

**Comment by gin66** [comment]
Your intention is to open a file, which contains log messages and use TuiLogger to display these entries ?

**Comment by EnricoMucelli** [comment]
> Your intention is to open a file, which contains log messages and use TuiLogger to display these entries ?

yep exatcly! <3

**Comment by EnricoMucelli** [comment]
> Your intention is to open a file, which contains log messages and use TuiLogger to display these entries ?

@gin66 yes exactly!

**Comment by gin66** [comment]
Reading the log from a file is not supported currently. You could read back on application side the log and feed it back into the logging system. 

If you like to implement this or a different solution, a PR would be appreciated.

**Comment by gin66** [comment]
stale
