### ISSUE TITLE
Migrate from tui to ratatui

### ISSUE THREAD

**Issue by dzfrias** [gin66/tui-logger#32]
With the recent release of [ratatui](https://github.com/tui-rs-revival/ratatui), the tui-rs revival project, I think it would be best to support the new version to help people convert over.

There are a few other crates moving already, like [ansi-to-tui](https://github.com/uttarayan21/ansi-to-tui).

**Comment by gin66** [comment]
I have added this as an optional feature: `ratatui-support`. The default tui feature need to be disabled.
Please try.

**Comment by dzfrias** [comment]
The ratatui-support feature works great, thanks!
