### ISSUE TITLE
Breaking change, termion dependency for ratatui

### ISSUE THREAD

**Issue by SLASHLogin** [gin66/tui-logger#43]
0.9.3, change introduced in c3ef34e48d52a804f29555adc8508c94f0521433, enables `termion` in `ratatui` when using `ratatui-support` feature. This is breaking change on systems which are not supported by `termion` (i.e., mainly Windows). This could be avoided by allowing users to just use `ratatui` feature, but this crate doesn't compile properly with it since it uses `#[cfg(not(feature = "ratatui-support"))]`. 
I think either all `cfg` expressions should be changed to `#[cfg(not(feature = "ratatui"))]` or even better `#[cfg(feature = "ratatui")]`, or the latest change in `Cargo.toml` should be reverted/reconsidered.

**Comment by gin66** [comment]
Thanks for reporting. Hopefully v0.9.4 fixes this issue and captures similar errors by means of github-actions.

**Comment by SLASHLogin** [comment]
Great, it's working now. You might want to consider yanking the previous version to prevent other users from having similar problems.

**Comment by gin66** [comment]
I do not think, it is necessary to yank the previous version. The issue has not impacted the actual module. Only the examples/demo was broken on windows.
