### ISSUE TITLE
Set ratatui as default feature in place of tui

### ISSUE THREAD

**Issue by Kryszak** [gin66/tui-logger#45]
As for 6 August 2023 tui repository is archived https://github.com/fdehau/tui-rs/issues/654.
I think it's time to make ratatui feature default one and tui support as legacy feature.
It might make it easier to keep up with new versions of ratatui (as for now tui-logger 0.9.5 doesn't work with ratatui 0.23.0.

**Comment by gin66** [comment]
Thanks for the hint. Actually, in this case tui support can be dropped and just point to the latest compatible one.

**Comment by Kryszak** [comment]
That's even better idea, for tui there are older crate versions. Looking forward to the updates!

**Comment by orhun** [comment]
I totally second this!

**Comment by gin66** [comment]
will make the change in next official release as soon as I have time.

**Comment by gin66** [comment]
Just have found out, that ratatui 0.23.0 still compiles with tui_logger, so I will keep it for now and the issue can be kept open.
