### ISSUE TITLE
`lazy_static!` `TUI_LOGGER` cannot leak private type `TuiLogger`

### ISSUE THREAD

**Issue by omelia-iliffe** [gin66/tui-logger#64]
Came across this compiler error,
```
error[E0446]: private type `TuiLogger` in public interface
   --> tui-logger-0.11.1/src/lib.rs:408:1
    |
342 |   struct TuiLogger {
    |   ---------------- `TuiLogger` declared as private
...
408 | / lazy_static! {
409 | |     pub static ref TUI_LOGGER: TuiLogger = {
410 | |         let hs = HotSelect {
411 | |             hashtable: HashMap::with_capacity(1000),
...   |
430 | |     };
431 | | }
    | |_^ can't leak private type

```
My work around has been to make the `TuiLogger` struct public. Happy to make a PR if that's the desired fix, but I don't understand enough about what is happening to know what else to try.

**Comment by gin66** [comment]
Just have rerun the github action. The error does not pop up with ubuntu-latest and its rust version. Perhaps I need to install current stable rust version to detect this.

Does it work to remove the `pub` in line 409 ?

**Comment by gin66** [comment]
checked with stable rustic 1.79.0 and nightly 1.81.0 
Both do not show this error.
What is your environment ?

**Comment by gin66** [comment]
Just checked the src/lib.rs and in that line, the `pub` does not exist.
Not sure, which version you use, but your problem seems not to be with tui_logger.

**Comment by omelia-iliffe** [comment]
apologies for the false issue, turns out the cached version in my .cargo had been modified and the `pub` in the static had been added. It must have been me sometime ago but I can't remember why I would have done that. 

Thanks heaps for looking into it, and sorry again for wasting your time.
