### ISSUE TITLE
Docs: Document use of tracing-subscriber

### ISSUE THREAD

**Issue by nick42d** [gin66/tui-logger#67]
Hi there, I'd like to work on this, so thought I'd log an issue first.

It would be nice to have some documentation and examples for use of tracing-subscriber. I got a bit confused running into #66 earlier today and think having a bit more info could potentially others.

Let me know if you're happy to accept a PR and if you have any preferences on how to implement.

**Comment by gin66** [comment]
Hello nick42d, thanks for your willingness to contribute and I am looking forward to your PR. I have no preferences, how to implement the changes or create the example. Only I like to point out, that cargo-rdme is used in github-actions. I am still not familiar with this, so any alternative approach is fine, too.
