### ISSUE TITLE
`v0.13` breaks setup using `tracing_subscriber_layer`

### ISSUE THREAD

**Issue by jesdazrez** [gin66/tui-logger#70]
Up until `v0.12.1` the tracing integration was working ok. However, the `v0.13` update results in no events being displayed by the widgets.

I suspect this is related to `move_events` now being called in a background task that's initialized when calling `init_logger`. However I can't use `init_logger` since that'll try to override (and error) the `tracing_log` integration I have already set up.

Is there a workaround for this that allows me to keep using `tracing_log`, i.e. to send events to the widgets without setting up `tui-logger` as the `log`'s global logger?

**Comment by gin66** [comment]
Thanks for the report. I assume the line 500 in lib.rs is problematic:
```
log::set_logger(&*TUI_LOGGER).map_err(|err| {TuiLoggerError::SetLoggerError(err)})
```

Could you please try by commenting this line out ? Without this line `init_logger` will still start the background thread but will not call `log::init_logger()`.  If this works, then that line can be disabled by conditional compilation, if the tracing feature is enabled.
