### ISSUE TITLE
Use without tui widget

### ISSUE THREAD

**Issue by rg3l3dr** [gin66/tui-logger#8]
Hello! Love this crate, we've been using it to log to our TUI app. 

I'm wondering if it's possible to simply display the log output to the terminal without running with TUI? Sometimes we disable TUI for debug purposes. I tried running without launching TUI using `RUST_LOG=info cargo run` but no log info is output to the terminal.

**Comment by gin66** [comment]
what comes close is to set the log_file to console with this function

ˋˋˋ
pub fn set_log_file(fname: &str) -> io::Result<()>
ˋˋˋ

and /dev/console as filename. This mechanism requires tui_logger::move_events() to be called regularly, what is normally done from the widget.

Alternatively, you could initialize another longer implementation of your choice.

**Comment by gin66** [comment]
stale
